- robots/Revvy/info.json
Revvy config fix:
M2 and M5 motors removed, S1 distance sensor removed
> Revvy config fix

- challenges/Let's get started/Basic Programming/info.json
- challenges/Let's get started/Hello World/info.json
Hello World and Basic Programming for release
> Hello World and Basic Programming for release

- challenges/Weekly Challenges/Long Shot/info.json
WC 4 ready for Wednesday release
> WC 4 ready for Wednesday release

- challenges/Let's get started/Advanced Programming/info.json
Advanced Programming challenge text correction true to false
> Advanced Programming challenge text correction true to false

- challenges/Weekly Challenges/Wheel Away/info.json
> Minor corrections in json file - WC6 - Wheel Away

- challenges/Weekly Challenges/Feed Your Pet/info.json
Feed Your Pet  WC8 being ready for release
> Feed Your Pet  WC8 being ready for release

- challenges/Weekly Challenges/JengaTM Tower/info.json
WC 10 - JengaTM ready to be published
> WC 10 - JengaTM ready to be published

- challenges/Weekly Challenges/Hit the Cups/info.json
- challenges/Weekly Challenges/Snow Rake/info.json
WC 12 and 13 discourse link being added
> Discourse link being added to WC 12 and 13

- challenges/Weekly Challenges/Collect the balls/info.json
- challenges/Weekly Challenges/Fork Lift part 1/info.json
- challenges/Weekly Challenges/Fork Lift part 2/info.json
- challenges/Weekly Challenges/Sort out the coins/info.json
WC 14 ready for release - Collect the balls
> WC 14 ready for release - Collect the balls

- challenges/Weekly Challenges/Fork Lift part 1/info.json
- challenges/Weekly Challenges/Fork Lift part 2/info.json
- challenges/Weekly Challenges/Zorro/info.json
WC15 - Zorro ready for release
> WC15 - Zorro ready for release

- challenges/Weekly Challenges/Bowling/info.json
- challenges/Weekly Challenges/Fork Lift part 1/info.json
- challenges/Weekly Challenges/Fork Lift part 2/info.json
- challenges/Weekly Challenges/Petanque/info.json
- challenges/Weekly Challenges/Sort out the coins/info.json
WC 16 - Petanque is ready to be released
> Weekly challenge 16 ready to release

- challenges/Weekly Challenges/Bowling/info.json
WC 17 - Bowling - Ready to release
> WC 17 - Bowling - Ready to release

- challenges/Weekly Challenges/Fork Lift part 1/info.json
Fork Lift 1 . WC 20 ready for Wednesday release
> Fork Lift 1 . WC 20 ready for Wednesday release

- challenges/Weekly Challenges/Fork Lift part 2/info.json
Fork Lift 2 . WC 21 ready for Wednesday release
> Fork Lift 2 . WC 21 ready for Wednesday release

- challenges/Weekly Challenges/Pour the pins/info.json
> Weekly Challenge 22 ready to release

- challenges/Weekly Challenges/Let's play football!/info.json
> WC 23 ready to release

- challenges/Weekly Challenges/Writing bot/info.json
Writing bot WC 24 to be released
> Writing bot WC 24 to be released

- challenges/Weekly Challenges/Lift it up!/info.json
WC 25 - Lift it up! is ready for Wednesday release
> WC 25 to be released

- challenges/Weekly Challenges/Water Pong/info.json
WC 26 - Water Pong to be released
> WC 26 - Water Pong to be released

- challenges/Weekly Challenges/Dancing bot/info.json
Weekly Challenge 27 to be released
> Dancing bot - WC27

- challenges/Weekly Challenges/Build a pyramid/info.json
> WC28 ready to release

- challenges/Weekly Challenges/Spinning Around/info.json
WC29-Spinning Around ready to release
> WC29-Spinning Around ready to release

- challenges/Weekly Challenges/Water the plants/info.json
> WC 30 ready for release

- challenges/Weekly Challenges/Robin Hood/info.json
WC32 Robin Hood ready for Wednesday release
> WC32 Robin Hood ready for Wednesday release

- challenges/Weekly Challenges/Follow the line/info.json
WC33 Follow the Line is ready for Wednesday release
> WC33 Follow the Line is ready for Wednesday release

- challenges/Weekly Challenges/Crane/info.json
WC33 Crane is ready for Wednesday release
> WC34 Crane is ready for Wednesday release

- challenges/Weekly Challenges/Draw a cobweb/info.json
WC35 Draw a cobweb is ready for Wednesday release
> WC35 Draw a cobweb is ready for Wednesday release

- challenges/Weekly Challenges/Fishing bot/info.json
WC36 Fishing bot is ready for Wednesday release
> WC36 Fishing bot is ready for Wednesday release

- challenges/Weekly Challenges/Gordian knot/info.json
WC38 - Gordian Knot is ready for Wednesday release
> WC38 - Gordian Knot is ready for Wednesday release

- challenges/Weekly Challenges/Braiding bot/info.json
WC39 - Braiding bot is ready for release
> WC39 - Braiding bot is ready for release

- challenges/Weekly Challenges/Speedy delivery/info.json
WC40 - Speedy delivery - is ready for Wed release
> WC40 - Speedy delivery - is ready for Wed release

- challenges/Weekly Challenges/Garbage truck/info.json
WC41 - Garbage truck - is ready for Wed release
> WC41 - Garbage truck - is ready for Wed release

- challenges/Weekly Challenges/Snake/info.json
WC 42 ready for Wednesday release
> WC 42 ready for Wednesday release

- challenges/Weekly Challenges/Cannon/info.json
WC 43 ready for Wednesday release
> WC 43 ready for Wednesday release

- challenges/Weekly Challenges/Reading bot/info.json
WC 44 - Reading bot is ready for Wednesday release
> WC 44 - Reading bot is ready for Wednesday release

- challenges/Weekly Challenges/Close the door/info.json
WC45 - Close the door is ready for Wednesday release
> WC45 - Close the door is ready for Wednesday release

- challenges/Weekly Challenges/Open the door/info.json
WC46 - Open the door is ready for Wednesday release
> WC46 - Open the door is ready for Wednesday release
